config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'login', sign_out: 'logout',
    password: 'secret', confirmation: 'verification',
    registration: 'register', edit: 'edit/profile'
  }, sign_out_via: [:get, :post]

  resources :foods
  resources :recipes do
    resources :recipe_foods
  end
  resources :users
  resources :public_recipes, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  put '/recipes/:id/toggle_public', to: 'recipes#toggle_public', as: 'toggle_recipe_public'
  put '/recipes/:id/add_to_shopping', to: 'recipes#add_to_shopping', as: 'add_to_shopping'
  # Defines the root path route ("/")
  # root "articles#index"
  root 'foods#index'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods
  validates :name, presence: true
  validates :preparation_time, numericality: { greater_than_or_equal_to: 0 }
  validates :cooking_time, numericality: { greater_than_or_equal_to: 0 }
  validates :user_id, presence: true

  scope :public_recipes, -> { where(public: true).order(created_at: :desc) }

  def toggle_public!
    update(public: !public)
  end

  def add_to_shopping!
    update(shopping_tag: !shopping_tag)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]
  load_and_authorize_resource

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.includes([:user]).where(user: current_user)
    # Recipe.where(user: current_user)
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])
    @food_recipe = RecipeFood.where(recipe_id: @recipe.id).includes([:food])
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  def toggle_public
    @recipe = Recipe.find(params[:id])
    @recipe.toggle_public!
    redirect_to recipe_path(@recipe)
  end

  def add_to_shopping
    @recipe = Recipe.find(params[:id])
    @recipe.add_to_shopping!
    redirect_to recipe_path(@recipe)
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = current_user.recipes.new(recipe_params)
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.number_field :preparation_time %>
  </div>

  <div>
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.number_field :cooking_time %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div class="checkbox-div">
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="recipe">
  <div>
    <p>
      <%= link_to recipe.name , recipe %>
    </p>
      <%= button_to "Delete recipe", recipe, method: :delete %>
      </div>
  <p>
    <%= recipe.description %>
  </p>
</div>

app/views/recipes/_recipe_food.html.erb
<div id="<%= dom_id recipe_food %>">
  <p>
    <strong>Quantity:</strong>
    <%= recipe_food.quantity %>
  </p>

  <p>
    <strong>User:</strong>
    <%= recipe_food.user_id %>
  </p>

  <p>
    <strong>Food:</strong>
    <%= recipe_food.food_id %>
  </p>

</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<div class="container">
  <% if notice.present? %>
    <p class="notice"><%= notice %></p>
  <% end %>

  <h1>Recipes</h1>

  <div id="recipes">
    <% if @recipes %>
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
  <% end %>
<% end %>

  <div class="new-recipe-link-div">
    <%= link_to "New recipe", new_recipe_path, class: "new-recipe-link" %>
  </div>
</div>

app/views/recipes/new.html.erb
<%= render "form", recipe: @recipe %>

<br>

<div class="new-recipe-link-div">
  <%= link_to "Back to recipes", recipes_path, class:"new-recipe-link" %>
</div>

app/views/recipes/show.html.erb
<div id="recipe-details">
  <h1><%= @recipe.name %></h1>

  <div class="recipe-box">
    <div class="recipe-details">
      <div class="recipe-detail">
        <p>Preparation time: <%= @recipe.preparation_time %> min</p>
      </div>
      <div class="recipe-detail">
        <p>Cooking time: <%= @recipe.cooking_time %> min</p>
      </div>
      <div class="recipe-detail">
        <p>Steps: <%= @recipe.description %></p>
      </div>
    </div>
    <% if can? :update, @recipe %>
      <%= button_to(@recipe.public? ? "Make Private" : "Make Public", toggle_recipe_public_path(@recipe), method: :put, class: "update-recipe") %>
      <% end %>
  </div>

  <div class="recipe-actions">
    <% if can? :update, @recipe %>
      <%= button_to(@recipe.shopping_tag? ? "Remove from shopping list" : "Generate shopping list", add_to_shopping_path(@recipe), method: :put, class: "update-recipe") %>
    <% end %>
  </div>
</div>

  
<div id="shopping_table">
  <table>
    <thead>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Value</th>
        <% if can? :destroy, @recipe %>
        <th>Actions</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @food_recipe.each do |recipe_food| %>
        <tr id="<%= dom_id recipe_food %>">
          <td><%= recipe_food.food.name %></td>
          <td><%= recipe_food.quantity %></td>
          <td><%= recipe_food.food.price * recipe_food.quantity %></td>
          <% if can? :destroy, @recipe %>
          <td>
          <%= button_to "Delete", recipe_recipe_food_path(@recipe, recipe_food), method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>