config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'login', sign_out: 'logout',
    password: 'secret', confirmation: 'verification',
    registration: 'register', edit: 'edit/profile'
  }, sign_out_via: [:get, :post]

  resources :foods
  resources :recipes do
    resources :recipe_foods
  end
  resources :users
  resources :public_recipes, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  put '/recipes/:id/toggle_public', to: 'recipes#toggle_public', as: 'toggle_recipe_public'
  put '/recipes/:id/add_to_shopping', to: 'recipes#add_to_shopping', as: 'add_to_shopping'
  # Defines the root path route ("/")
  # root "articles#index"
  root 'foods#index'
end

app/views/layouts/_nav.html.erb
<ul class="nav-bar">
  <% if user_signed_in? %>
  <li class="nav-item profil">
    <h2>
      <%= "#{current_user.name}" %>
    </h2>
  </li>
  <% else %>
  <li class="nav-item profil">
    <h2>
    Recipe App
    </h2>
  </li>
  <% end %>

  </li>
  <li class="nav-item nav-link">
    <%= link_to 'Food List', foods_path, class: "nav-link" %> 
  </li>
  <li class="nav-item nav-link">
    <%= link_to 'Recipe List', recipes_path, class: "nav-link" %> 
  </li>
  <li class="nav-item nav-link">
    <%= link_to 'Public Recipe List', public_recipes_path, class: "nav-link" %> 
  </li>
  <li class="nav-item nav-link">
    <%= link_to 'General Shopping List', recipes_path, class: "nav-link" %> 
  </li>
  <% if user_signed_in? %>
    <li class="nav-item log">
      <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
    </li>
    <% else %>
    <li class="nav-item log">
      <%= link_to "Log in", new_session_path(resource_name), class: "nav-link" %>
    </li>
    <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/nav' %>

    <p class="notice flex-center"><%= notice %></p>
    <p class="alert flex-center"><%= alert %></p>

    <main id = "main-section">
    <%= yield %>
    </main>

    <footer id = "footer">
         <p>Created by Mathew &copy; <%= Time.now.year %> </p>
    </footer>
  </body>
</html>